const FeaturedData = [
  {
    featured_id: "Grass_Stage_2_Airdrop_2025",
    featured_title: "Grass (Stage 2)",
    featured_image:
      "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2FGrass-Stage-2.webp?alt=media&token=2515246c-51c8-4f1c-a5db-cf590b3d791e",
      company_logo:"https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2Fgrass.jpg?alt=media&token=d846518f-0a6b-485c-b5c1-3fb56f06e88f",
    category: "featured",
    description:
      "Grass Points can be earned in several ways. Currently, users can earn points by downloading and running the Grass desktop app, as well as referring new users.",
      type:"Stage 2🔥",
      type2:"Web Mining ⛏️",
    steps: [
      "Go to the official Grass platform https://app.getgrass.io/register/?referralCode=sSlCpigoGJeZbzM",
      "Create an account or log in if you already have one.",
      "Click on the “Connect” button to link your wallet or account.",
      "Download any necessary extensions or applications, like the Desktop Node, Lite Node (Chrome Extension)",
      "Follow @getgrass_io on X.",
      "Like and retweet the official airdrop announcement.",
      "Share your unique referral link with friends to gain extra points.",
      "Check the platform’s blog or updates for additional reward opportunities.",
      "Track your points or rewards within your account dashboard.",
      "Follow @rairdropinfiniti for regular updates and upcoming opportunities. https://x.com/@airdropinfiniti to follow.",
    ],
    availability: true,
    price: 500,
    listed_price:3,
    network: "Solana ",
    network_logo: "https://cryptologos.cc/logos/solana-sol-logo.png?v=035",
    task: "Running Desktop Node(2x earning), Network mining, Referral",
  },
  {
    featured_id: "Grass_Stage_2_Airdrop_2025",
    featured_title: "Grass (Stage 2)",
    featured_image:
      "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2FGrass-Stage-2.webp?alt=media&token=2515246c-51c8-4f1c-a5db-cf590b3d791e",
      company_logo:"https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2Fgrass.jpg?alt=media&token=d846518f-0a6b-485c-b5c1-3fb56f06e88f",
    category: "new",
    description:
      "Grass Points can be earned in several ways. Currently, users can earn points by downloading and running the Grass desktop app, as well as referring new users.",
      descriptionS:"users can earn points by downloading and running the Grass desktop app",
    steps: [
      "Go to the official Grass platform https://app.getgrass.io/register/?referralCode=sSlCpigoGJeZbzM",
      "Create an account or log in if you already have one.",
      "Click on the “Connect” button to link your wallet or account.",
      "Download any necessary extensions or applications, like the Desktop Node, Lite Node (Chrome Extension)",
      "Follow @getgrass_io on X.",
      "Like and retweet the official airdrop announcement.",
      "Share your unique referral link with friends to gain extra points.",
      "Check the platform’s blog or updates for additional reward opportunities.",
      "Track your points or rewards within your account dashboard.",
      "Follow @rairdropinfiniti for regular updates and upcoming opportunities. https://x.com/@airdropinfiniti to follow.",
    ],
    availability: true,
    price: 500,
    listed_price:3,
    network: "Solana",
    task: "Running Desktop Node(2x earning), Network mining, Referral",
  },
  {
    featured_id: "Grass_Stage_2_Airdrop_2025",
    featured_title: "Grass (Stage 2)",
    featured_image:
      "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2FGrass-Stage-2.webp?alt=media&token=2515246c-51c8-4f1c-a5db-cf590b3d791e",
      company_logo:"https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2Fgrass.jpg?alt=media&token=d846518f-0a6b-485c-b5c1-3fb56f06e88f",
    category: "telegram",
    description:
      "Grass Points can be earned in several ways. Currently, users can earn points by downloading and running the Grass desktop app, as well as referring new users.",
      descriptionS:"users can earn points by downloading and running the Grass desktop app",
    steps: [
      "Go to the official Grass platform https://app.getgrass.io/register/?referralCode=sSlCpigoGJeZbzM",
      "Create an account or log in if you already have one.",
      "Click on the “Connect” button to link your wallet or account.",
      "Download any necessary extensions or applications, like the Desktop Node, Lite Node (Chrome Extension)",
      "Follow @getgrass_io on X.",
      "Like and retweet the official airdrop announcement.",
      "Share your unique referral link with friends to gain extra points.",
      "Check the platform’s blog or updates for additional reward opportunities.",
      "Track your points or rewards within your account dashboard.",
      "Follow @rairdropinfiniti for regular updates and upcoming opportunities. https://x.com/@airdropinfiniti to follow.",
    ],
    availability: true,
    price: 500,
    listed_price:3,
    network: "Solana",
    task: "Running Desktop Node(2x earning), Network mining, Referral",
  },
  {
    featured_id: "Grass_Stage_2_Airdrop_2025",
    featured_title: "Grass (Stage 2)",
    featured_image:
      "https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2FGrass-Stage-2.webp?alt=media&token=2515246c-51c8-4f1c-a5db-cf590b3d791e",
      company_logo:"https://firebasestorage.googleapis.com/v0/b/sajid-hossain.appspot.com/o/Airdrop%20Infinity%2Fgrass.jpg?alt=media&token=d846518f-0a6b-485c-b5c1-3fb56f06e88f",
    category: "exchange",
    description:
      "Grass Points can be earned in several ways. Currently, users can earn points by downloading and running the Grass desktop app, as well as referring new users.",
      descriptionS:"users can earn points by downloading and running the Grass desktop app",
    steps: [
      "Go to the official Grass platform https://app.getgrass.io/register/?referralCode=sSlCpigoGJeZbzM",
      "Create an account or log in if you already have one.",
      "Click on the “Connect” button to link your wallet or account.",
      "Download any necessary extensions or applications, like the Desktop Node, Lite Node (Chrome Extension)",
      "Follow @getgrass_io on X.",
      "Like and retweet the official airdrop announcement.",
      "Share your unique referral link with friends to gain extra points.",
      "Check the platform’s blog or updates for additional reward opportunities.",
      "Track your points or rewards within your account dashboard.",
      "Follow @rairdropinfiniti for regular updates and upcoming opportunities. https://x.com/@airdropinfiniti to follow.",
    ],
    availability: true,
    price: 500,
    listed_price:3,
    network: "Solana",
    task: "Running Desktop Node(2x earning), Network mining, Referral",
  },
    ];

export default FeaturedData;
